//! The crate that hands a program a profile.
//!
//! ⭐ **A dependency line instead of three decisions.** A consumer that wants a
//! User-Agent should not have to fetch a file, parse it and know its shape;
//! that is the reason people copy values by hand, and copying by hand is what
//! this whole project exists to stop.
//!
//! ```no_run
//! use b_ids::{Version, select, user_agent};
//! use b_ids::schema::Channel;
//!
//! let profile = select("chrome", Channel::Stable, "linux64", Version::Latest)
//!     .expect("this corpus holds one");
//! println!("{}", user_agent(profile).unwrap_or("not recorded"));
//! ```
//!
//! # ⛔ What this crate refuses to do
//!
//! - **It does not fetch.** There is no network code here at all. The corpus is
//!   embedded at build time and [`release`] says which one, so a consumer can
//!   tell how old their data is without leaving their language.
//! - **It does not substitute.** [`select`] returns [`None`] for a platform
//!   this project has not captured. Returning a neighbouring platform's profile
//!   would put an unmeasured value behind a measured interface, which is the
//!   same rule the published routes hold: a missing route is a fact and a
//!   substituted value is a lie.
//! - **It does not assemble.** There is no builder that takes the TLS half of
//!   one profile and the headers of another. A combination nothing measured is
//!   more distinguishing than an honestly old one.
//! - **It does not hide provenance.** [`schema::Profile::provenance`] is part of
//!   the public shape, because a consumer has to be able to ask whether a field
//!   was measured.
//!
//! # ⚠ What it costs, and it is written down rather than discovered
//!
//! ⛔ **Nothing here links the harness or the corpus tooling.** `b-ids-corpus`
//! says in its own manifest that a consumer who only wants to READ the corpus
//! should not link the TLS terminator through it, and names this entry as where
//! the read-only path belongs. So the runtime dependencies are the model and a
//! JSON parser, and the digest that pins the corpus is computed by a BUILD
//! dependency instead.
//!
//! ⚠ **`latest` is READ, never derived.** The corpus publishes a pointer file
//! and this crate looks the answer up in it. Deriving "which build is newest"
//! here would be a second implementation of a rule the corpus already holds,
//! and the day the two disagreed the consumer would be the one who found out.
//!
//! `docs/history/todo/library.md`, `LIB-01`.

use std::sync::OnceLock;

pub use b_ids_schema as schema;
use b_ids_schema::http::{HeaderField, Variant};
use b_ids_schema::{Channel, Digests, Profile};

// ⛔ GENERATED BY build.rs FROM THE INDEX, never written by hand. It defines
// `RELEASE`, `POINTERS_JSON` and `PROFILES`.
include!(concat!(env!("OUT_DIR"), "/corpus.rs"));

/// Which build a caller wants.
///
/// ⛔ **There is no "closest" and there never will be.** A version this corpus
/// does not hold is absent, and a caller that wants the newest asks for the
/// newest by name.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Version<'a> {
    /// The newest build the corpus holds on the named channel.
    ///
    /// ⚠ Resolved through the corpus's own pointer file rather than by
    /// comparing versions here.
    Latest,
    /// One exact build, as the browser spells it.
    Exact(&'a str),
}

/// What corpus this build embedded.
///
/// ⭐ **A field a program can read**, so a consumer can tell how old their data
/// is without leaving their language.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Release {
    /// The SHA-256 of the corpus index, lowercase hex.
    ///
    /// ⛔ **This is the pin.** The index carries a digest of every published
    /// file, so an identifier over the index pins the corpus transitively: two
    /// builds reporting the same identifier embedded the same bytes.
    pub identifier: &'static str,
    /// The layout version every embedded profile is published under.
    pub layout: String,
    /// How many profiles are embedded.
    pub profiles: usize,
    /// The newest capture instant among them, as the profiles spell it.
    ///
    /// ⚠ [`None`] where the corpus is empty, which is a state this crate can be
    /// built in and not one it can be used in.
    pub newest_capture: Option<String>,
}

/// The embedded profiles, parsed once, in the index's own order.
///
/// ⛔ **A profile the model cannot parse is a panic here rather than a silent
/// omission.** A corpus that is quietly smaller than the one this crate names
/// is worse than one that will not load, because the first is invisible.
#[must_use]
pub fn profiles() -> &'static [Profile] {
    static PARSED: OnceLock<Vec<Profile>> = OnceLock::new();
    PARSED
        .get_or_init(|| {
            PROFILES
                .iter()
                .map(|(path, text)| {
                    serde_json::from_str(text)
                        .unwrap_or_else(|e| panic!("b-ids: {path} is not a profile: {e}"))
                })
                .collect()
        })
        .as_slice()
}

/// The published path of each embedded profile, in the same order as
/// [`profiles`].
#[must_use]
pub fn paths() -> &'static [&'static str] {
    static PATHS: OnceLock<Vec<&'static str>> = OnceLock::new();
    PATHS
        .get_or_init(|| PROFILES.iter().map(|(path, _)| *path).collect())
        .as_slice()
}

/// What corpus this build embedded.
#[must_use]
pub fn release() -> &'static Release {
    static RELEASED: OnceLock<Release> = OnceLock::new();
    RELEASED.get_or_init(|| {
        let newest = profiles().iter().map(|p| p.captured.at.clone()).max();
        Release {
            identifier: RELEASE,
            layout: pointers().layout.clone(),
            profiles: profiles().len(),
            newest_capture: newest,
        }
    })
}

/// The corpus's own pointer file, parsed once.
fn pointers() -> &'static Pointers {
    static PARSED: OnceLock<Pointers> = OnceLock::new();
    PARSED.get_or_init(|| {
        serde_json::from_str(POINTERS_JSON)
            .unwrap_or_else(|e| panic!("b-ids: the embedded pointer file is not one: {e}"))
    })
}

/// The pointers the corpus publishes, as this crate reads them.
///
/// ⚠ **A reader of the published file, not a second definition of it.** The
/// corpus decides what `latest` means; this only follows the answer.
#[derive(Debug, Clone, PartialEq, Eq, serde::Deserialize)]
struct Pointers {
    layout: String,
    #[serde(default)]
    latest: std::collections::BTreeMap<String, String>,
    #[serde(default)]
    per_channel: std::collections::BTreeMap<String, String>,
}

/// One profile, by browser, channel, platform and version.
///
/// ⛔ **Returns [`None`] rather than a substitute.** A platform this project has
/// not captured has no profile, and a neighbouring platform's would be an
/// unmeasured value behind a measured interface.
///
/// ⚠ The browser and the platform are matched the way the published routes
/// spell them, which is lower case.
#[must_use]
pub fn select(
    browser: &str,
    channel: Channel,
    platform: &str,
    version: Version<'_>,
) -> Option<&'static Profile> {
    let browser = browser.to_ascii_lowercase();
    let platform = platform.to_ascii_lowercase();
    match version {
        Version::Exact(wanted) => profiles().iter().find(|p| {
            p.browser.name.to_ascii_lowercase() == browser
                && p.browser.channel == channel
                && p.platform_token().as_str() == platform
                && p.browser.version == wanted
        }),
        Version::Latest => {
            // ⛔ THE POINTER FILE ANSWERS THIS, and it is keyed by
            // browser/channel/platform. `latest` on its own means STABLE in the
            // corpus, and this crate does not widen that.
            let key = format!("{browser}/{}/{platform}", channel.as_str());
            let path = pointers().per_channel.get(&key)?;
            at(path)
        }
    }
}

/// The newest stable build for a browser on a platform.
///
/// ⭐ **The pointer a script follows.** `latest` means stable and nothing else,
/// which is the corpus's rule rather than this crate's, so a consumer following
/// it is never handed a pre-release build.
#[must_use]
pub fn latest_stable(browser: &str, platform: &str) -> Option<&'static Profile> {
    let key = format!(
        "{}/{}",
        browser.to_ascii_lowercase(),
        platform.to_ascii_lowercase()
    );
    at(pointers().latest.get(&key)?)
}

/// The profile published at one path.
///
/// ⚠ **Keyed by the path the index gave**, so nothing here parses a route. The
/// layout belongs to the corpus and a second reading of it would be a second
/// place for it to be wrong.
#[must_use]
pub fn at(path: &str) -> Option<&'static Profile> {
    let index = paths().iter().position(|p| *p == path)?;
    profiles().get(index)
}

/// The User-Agent this build sends on a navigation.
///
/// ⚠ [`None`] where the profile records header NAMES only, which is the
/// default: a capture turns values on deliberately.
#[must_use]
pub fn user_agent(profile: &Profile) -> Option<&str> {
    header(profile, Variant::Navigate, "user-agent")
}

/// The client hints this build sends on a navigation, in wire order.
///
/// ⚠ Only the ones whose value was recorded. A hint whose name is recorded and
/// whose value is not is absent here and present in
/// [`header_order`], which is the honest split.
#[must_use]
pub fn client_hints(profile: &Profile) -> Vec<(&str, &str)> {
    fields(profile, Variant::Navigate)
        .filter(|f| f.name.to_ascii_lowercase().starts_with("sec-ch-"))
        .filter_map(|f| Some((f.name.as_str(), f.value.as_deref()?)))
        .collect()
}

/// The header names this build sends, in wire order.
///
/// ⭐ **The order is the fingerprint.** A caller that sorts this has thrown away
/// the thing it asked for.
#[must_use]
pub fn header_order(profile: &Profile, variant: Variant) -> Vec<&str> {
    fields(profile, variant).map(|f| f.name.as_str()).collect()
}

/// One recorded header value of one request variant.
#[must_use]
pub fn header<'a>(profile: &'a Profile, variant: Variant, name: &str) -> Option<&'a str> {
    fields(profile, variant)
        .find(|f| f.name.eq_ignore_ascii_case(name))?
        .value
        .as_deref()
}

/// The `ClientHello` this project read off the wire, hex-encoded.
///
/// ⭐ **The one artefact in which a GREASE question is answerable at all**,
/// because every digest strips GREASE before it is computed.
#[must_use]
pub fn client_hello_hex(profile: &Profile) -> Option<&str> {
    profile.raw.client_hello_hex.as_deref()
}

/// The digests this project derived for a profile.
///
/// ⚠ **Every one of them is an [`Option`]**, and a corpus that has not computed
/// one says so rather than serving a zero.
#[must_use]
pub fn digests(profile: &Profile) -> &Digests {
    &profile.digests
}

/// The header fields of one request variant, in wire order.
fn fields(profile: &Profile, variant: Variant) -> impl Iterator<Item = &HeaderField> {
    profile
        .http
        .variant(variant)
        .into_iter()
        .flat_map(|set| set.headers.iter())
}
